use lastmile_report;

drop view if exists lastmile_report.view_chss_msr;

create view lastmile_report.view_chss_msr as

select 
        `lastmile_report`.`territory_id`(`a`.`county`, 1) AS `territory_id`,
        `a`.`chss_monthly_service_report_id` AS `chss_monthly_service_report_id`,
        `a`.`meta_uuid` AS `meta_uuid`,
        `a`.`meta_de_init` AS `meta_de_init`,
        `a`.`meta_de_date` AS `meta_de_date`,
        `a`.`meta_de_time_start` AS `meta_de_time_start`,
        `a`.`meta_de_time_end` AS `meta_de_time_end`,
        `a`.`meta_qa_init` AS `meta_qa_init`,
        `a`.`meta_qa_date` AS `meta_qa_date`,
        `a`.`meta_data_source` AS `meta_data_source`,
        `a`.`meta_form_version` AS `meta_form_version`,
        `a`.`meta_insert_date_time` AS `meta_insert_date_time`,
        `a`.`meta_fabricated` AS `meta_fabricated`,
        `a`.`chss_name` AS `chss_name`,
        `a`.`chss_id` AS `chss_id`,
        `a`.`chss_id_inserted` AS `chss_id_inserted`,
        `a`.`district` AS `district`,
        `a`.`month_reported` AS `month_reported`,
        `a`.`county` AS `county`,
        `a`.`health_facility` AS `health_facility`,
        `a`.`health_facility_id` AS `health_facility_id`,
        `a`.`year_reported` AS `year_reported`,
        `a`.`cha_id_1` AS `cha_id_1`,
        `a`.`cha_id_1_inserted` AS `cha_id_1_inserted`,
        `a`.`cha_id_2` AS `cha_id_2`,
        `a`.`cha_id_2_inserted` AS `cha_id_2_inserted`,
        `a`.`cha_id_3` AS `cha_id_3`,
        `a`.`cha_id_3_inserted` AS `cha_id_3_inserted`,
        `a`.`cha_id_4` AS `cha_id_4`,
        `a`.`cha_id_4_inserted` AS `cha_id_4_inserted`,
        `a`.`cha_id_5` AS `cha_id_5`,
        `a`.`cha_id_5_inserted` AS `cha_id_5_inserted`,
        `a`.`cha_id_6` AS `cha_id_6`,
        `a`.`cha_id_6_inserted` AS `cha_id_6_inserted`,
        `a`.`cha_id_7` AS `cha_id_7`,
        `a`.`cha_id_7_inserted` AS `cha_id_7_inserted`,
        `a`.`cha_id_8` AS `cha_id_8`,
        `a`.`cha_id_8_inserted` AS `cha_id_8_inserted`,
        `a`.`cha_id_9` AS `cha_id_9`,
        `a`.`cha_id_9_inserted` AS `cha_id_9_inserted`,
        `a`.`cha_id_10` AS `cha_id_10`,
        `a`.`cha_id_10_inserted` AS `cha_id_10_inserted`,
        `a`.`cha_id_11` AS `cha_id_11`,
        `a`.`cha_id_11_inserted` AS `cha_id_11_inserted`,
        `a`.`cha_id_12` AS `cha_id_12`,
        `a`.`cha_id_12_inserted` AS `cha_id_12_inserted`,
        `a`.`cha_id_13` AS `cha_id_13`,
        `a`.`cha_id_13_inserted` AS `cha_id_13_inserted`,
        `a`.`cha_id_14` AS `cha_id_14`,
        `a`.`cha_id_14_inserted` AS `cha_id_14_inserted`,
        `a`.`5_3_a_supervision_visits_completed` AS `5_3_a_supervision_visits_completed`,
        `a`.`5_3_b_number_cha_absences` AS `5_3_b_number_cha_absences`,
        `a`.`5_3_c_reviews_completed` AS `5_3_c_reviews_completed`,
        `a`.`5_3_d_reviews_correct_treatment` AS `5_3_d_reviews_correct_treatment`,
        `a`.`5_3_e_cha_reports_on_time` AS `5_3_e_cha_reports_on_time`,
        `a`.`1_2_a_routine_household_visits` AS `1_2_a_routine_household_visits`,
        `a`.`1_2_b_births_community_home` AS `1_2_b_births_community_home`,
        `a`.`1_2_c_births_facility` AS `1_2_c_births_facility`,
        `a`.`1_2_d_still_births` AS `1_2_d_still_births`,
        `a`.`1_2_e_neonatal_deaths` AS `1_2_e_neonatal_deaths`,
        `a`.`1_2_f_post_neonatal_deaths` AS `1_2_f_post_neonatal_deaths`,
        `a`.`1_2_g_child_deaths` AS `1_2_g_child_deaths`,
        `a`.`1_2_h_maternal_deaths` AS `1_2_h_maternal_deaths`,
        `a`.`1_2_i_community_triggers` AS `1_2_i_community_triggers`,
        `a`.`1_2_j_hiv_tb_cm_ntd_mh_suspect_referrals` AS `1_2_j_hiv_tb_cm_ntd_mh_suspect_referrals`,
        `a`.`2_1_a_pregnant_woman_visits` AS `2_1_a_pregnant_woman_visits`,
        `a`.`2_1_b_referred_delivery` AS `2_1_b_referred_delivery`,
        `a`.`2_1_c_referred_anc` AS `2_1_c_referred_anc`,
        `a`.`2_1_d_post_natal_visits` AS `2_1_d_post_natal_visits`,
        `a`.`2_1_e_referred_danger_sign` AS `2_1_e_referred_danger_sign`,
        `a`.`2_1_f_hbmnc_48_hours_mother` AS `2_1_f_hbmnc_48_hours_mother`,
        `a`.`2_1_g_hbmnc_48_hours_infant` AS `2_1_g_hbmnc_48_hours_infant`,
        `a`.`2_2_a_clients_modern_fp` AS `2_2_a_clients_modern_fp`,
        `a`.`3_1_a_active_case_finds` AS `3_1_a_active_case_finds`,
        `a`.`3_1_b_muac_red` AS `3_1_b_muac_red`,
        `a`.`3_1_c_muac_yellow` AS `3_1_c_muac_yellow`,
        `a`.`3_1_d_muac_green` AS `3_1_d_muac_green`,
        `a`.`3_1_e_pneumonia_cases` AS `3_1_e_pneumonia_cases`,
        `a`.`3_1_f_malaria_rdt` AS `3_1_f_malaria_rdt`,
        `a`.`3_1_g_diarrhea_cases` AS `3_1_g_diarrhea_cases`,
        `a`.`3_1_h_pneumonia_treated_antibiotics` AS `3_1_h_pneumonia_treated_antibiotics`,
        `a`.`3_1_i_malaria_treated_2_11_months` AS `3_1_i_malaria_treated_2_11_months`,
        `a`.`3_1_j_malaria_treated_1_5_years` AS `3_1_j_malaria_treated_1_5_years`,
        `a`.`3_1_k_malaria_treated_less_24_hours` AS `3_1_k_malaria_treated_less_24_hours`,
        `a`.`3_1_l_malaria_treated_more_24_hours` AS `3_1_l_malaria_treated_more_24_hours`,
        `a`.`3_1_m_diarrhea_treated_zinc_ors` AS `3_1_m_diarrhea_treated_zinc_ors`,
        `a`.`3_1_n_referred_health_facility` AS `3_1_n_referred_health_facility`,
        `a`.`4_1_a_hiv_client_visits` AS `4_1_a_hiv_client_visits`,
        `a`.`4_1_b_tb_client_visits` AS `4_1_b_tb_client_visits`,
        `a`.`4_1_c_cm_ntd_client_visits` AS `4_1_c_cm_ntd_client_visits`,
        `a`.`4_1_d_mental_health_client_visits` AS `4_1_d_mental_health_client_visits`,
        `a`.`4_1_e_ltfu_hiv_clients_traced` AS `4_1_e_ltfu_hiv_clients_traced`,
        `a`.`4_1_f_ltfu_tb_clients_traced` AS `4_1_f_ltfu_tb_clients_traced`
    FROM `lastmile_upload`.`de_chss_monthly_service_report` `a`
    where not ( trim( chss_id ) like '999' )
;