/*

  Federated table federated_de_integrated_supervision_tool_facility connects to a table of the same name 
  in the same schema liberiad_upload on the MySQL instance on server 97.74.233.76.  This server
  host the liberiamohdata.com website where the IFI data is collected.
  
*/

use lastmile_liberiamohdata;

drop table if exists federated_de_integrated_supervision_tool_facility;

create table federated_de_integrated_supervision_tool_facility (

  id int( 10 )            not null auto_increment,
  
  meta_uuid varchar(255) NOT NULL,
  meta_de_init varchar(100) DEFAULT NULL,
  meta_de_date varchar(100) DEFAULT NULL,
  meta_de_time_start time DEFAULT NULL,
  meta_de_time_end time DEFAULT NULL,
  meta_qa_init varchar(100) DEFAULT NULL,
  meta_qa_date varchar(100) DEFAULT NULL,
  meta_data_source varchar(100) DEFAULT NULL,
  meta_form_version varchar(100) DEFAULT NULL,
  meta_insert_date_time datetime DEFAULT NULL,
  data_collector_team varchar(100) DEFAULT NULL,
  county varchar(100) DEFAULT NULL,
  health_district varchar(100) DEFAULT NULL,
  facility varchar(100) DEFAULT NULL,
  month_complete varchar(100) DEFAULT NULL,
  day_complete varchar(100) DEFAULT NULL,
  year_complete varchar(100) DEFAULT NULL,
  chss_id varchar(100) DEFAULT NULL,
  chss varchar(100) DEFAULT NULL,
  chss_gender varchar(100) DEFAULT NULL,
  oic varchar(100) DEFAULT NULL,
  oic_gender varchar(100) DEFAULT NULL,
  data_collector_name varchar(100) DEFAULT NULL,
  data_collector_position varchar(100) DEFAULT NULL,
  supervision_time_start varchar(100) DEFAULT NULL,
  supervision_time_end varchar(100) DEFAULT NULL,
  1_1_community_engagement_number_meet_hfdc_chsss varchar(100) DEFAULT NULL,
  1_2_community_engagement_documented_meeting_minutes varchar(100) DEFAULT NULL,
  1_3_community_engagement_stakeholder_aware_health_program varchar(100) DEFAULT NULL,
  2_1_incentive_correct_amount varchar(100) DEFAULT NULL,
  2_2_incentive_on_time varchar(100) DEFAULT NULL,
  2_incentive_incorrect varchar(100) DEFAULT NULL,
  2_3_incentive_payment_month varchar(100) DEFAULT NULL,
  2_3_incentive_payment_day varchar(100) DEFAULT NULL,
  2_3_incentive_payment_year varchar(100) DEFAULT NULL,
  3_1_supply_locked_box_cha varchar(100) DEFAULT NULL,
  3_2_a_supply_microlut_ocp_in_stock varchar(100) DEFAULT NULL,
  3_2_a_supply_microlut_ocp_stock_out_month varchar(100) DEFAULT NULL,
  3_2_a_supply_microlut_ocp_stock_out_day varchar(100) DEFAULT NULL,
  3_2_a_supply_microlut_ocp_stock_out_year varchar(100) DEFAULT NULL,
  3_2_b_supply_microgynon_ocp_in_stock varchar(100) DEFAULT NULL,
  3_2_b_supply_microgynon_ocp_stock_out_month varchar(100) DEFAULT NULL,
  3_2_b_supply_microgynon_ocp_stock_out_day varchar(100) DEFAULT NULL,
  3_2_b_supply_microgynon_ocp_stock_out_year varchar(100) DEFAULT NULL,
  3_2_c_supply_male_condom_in_stock varchar(100) DEFAULT NULL,
  3_2_c_supply_male_condom_stock_out_month varchar(100) DEFAULT NULL,
  3_2_c_supply_male_condom_stock_out_day varchar(100) DEFAULT NULL,
  3_2_c_supply_male_condom_stock_out_year varchar(100) DEFAULT NULL,
  3_2_d_supply_female_condom_in_stock varchar(100) DEFAULT NULL,
  3_2_d_supply_female_condom_stock_out_month varchar(100) DEFAULT NULL,
  3_2_d_supply_female_condom_stock_out_day varchar(100) DEFAULT NULL,
  3_2_d_supply_female_condom_stock_out_year varchar(100) DEFAULT NULL,
  3_2_e_supply_disposable_glove_in_stock varchar(100) DEFAULT NULL,
  3_2_e_supply_disposable_glove_stock_out_month varchar(100) DEFAULT NULL,
  3_2_e_supply_disposable_glove_stock_out_day varchar(100) DEFAULT NULL,
  3_2_e_supply_disposable_glove_stock_out_year varchar(100) DEFAULT NULL,
  3_2_f_supply_act_25_67_5_mg_tablet_in_stock varchar(100) DEFAULT NULL,
  3_2_f_supply_act_25_67_5_mg_tablet_stock_out_month varchar(100) DEFAULT NULL,
  3_2_f_supply_act_25_67_5_mg_tablet_stock_out_day varchar(100) DEFAULT NULL,
  3_2_f_supply_act_25_67_5_mg_tablet_stock_out_year varchar(100) DEFAULT NULL,
  3_2_g_supply_act_50_135_mg_tablet_in_stock varchar(100) DEFAULT NULL,
  3_2_g_supply_act_50_135_mg_tablet_stock_out_month varchar(100) DEFAULT NULL,
  3_2_g_supply_act_50_135_mg_tablet_stock_out_day varchar(100) DEFAULT NULL,
  3_2_g_supply_act_50_135_mg_tablet_stock_out_year varchar(100) DEFAULT NULL,
  3_2_h_supply_artesunate_100_mg_suppository_in_stock varchar(100) DEFAULT NULL,
  3_2_h_supply_artesunate_100_mg_suppository_stock_out_month varchar(100) DEFAULT NULL,
  3_2_h_supply_artesunate_100_mg_suppository_stock_out_day varchar(100) DEFAULT NULL,
  3_2_h_supply_artesunate_100_mg_suppository_stock_out_year varchar(100) DEFAULT NULL,
  3_2_i_supply_amox_250_mg_dispersible_tablet_in_stock varchar(100) DEFAULT NULL,
  3_2_i_supply_amox_250_mg_dispersible_tablet_stock_out_month varchar(100) DEFAULT NULL,
  3_2_i_supply_amox_250_mg_dispersible_tablet_stock_out_day varchar(100) DEFAULT NULL,
  3_2_i_supply_amox_250_mg_dispersible_tablet_stock_out_year varchar(100) DEFAULT NULL,
  3_2_j_supply_ors_20_6_1l_sachet_in_stock varchar(100) DEFAULT NULL,
  3_2_j_supply_ors_20_6_1l_sachet_stock_out_month varchar(100) DEFAULT NULL,
  3_2_j_supply_ors_20_6_1l_sachet_stock_out_day varchar(100) DEFAULT NULL,
  3_2_j_supply_ors_20_6_1l_sachet_stock_out_year varchar(100) DEFAULT NULL,
  3_2_k_supply_zinc_sulfate_20_mg_scored_tablet_in_stock varchar(100) DEFAULT NULL,
  3_2_k_supply_zinc_sulfate_20_mg_scored_tablet_stock_out_month varchar(100) DEFAULT NULL,
  3_2_k_supply_zinc_sulfate_20_mg_scored_tablet_stock_out_day varchar(100) DEFAULT NULL,
  3_2_k_supply_zinc_sulfate_20_mg_scored_tablet_stock_out_year varchar(100) DEFAULT NULL,
  3_2_l_supply_paracetamol_100_mg_disp_tablet_in_stock varchar(100) DEFAULT NULL,
  3_2_l_supply_paracetamol_100_mg_disp_tablet_stock_out_month varchar(100) DEFAULT NULL,
  3_2_l_supply_paracetamol_100_mg_disp_tablet_stock_out_day varchar(100) DEFAULT NULL,
  3_2_l_supply_paracetamol_100_mg_disp_tablet_stock_out_year varchar(100) DEFAULT NULL,
  3_2_m_supply_muac_strap_in_stock varchar(100) DEFAULT NULL,
  3_2_m_supply_muac_strap_stock_out_month varchar(100) DEFAULT NULL,
  3_2_m_supply_muac_strap_stock_out_day varchar(100) DEFAULT NULL,
  3_2_m_supply_muac_strap_stock_out_year varchar(100) DEFAULT NULL,
  3_2_n_supply_dispensing_bag_in_stock varchar(100) DEFAULT NULL,
  3_2_n_supply_dispensing_bag_stock_out_month varchar(100) DEFAULT NULL,
  3_2_n_supply_dispensing_bag_stock_out_day varchar(100) DEFAULT NULL,
  3_2_n_supply_dispensing_bag_stock_out_year varchar(100) DEFAULT NULL,
  3_2_o_supply_safety_box_in_stock varchar(100) DEFAULT NULL,
  3_2_o_supply_safety_box_stock_out_month varchar(100) DEFAULT NULL,
  3_2_o_supply_safety_box_stock_out_day varchar(100) DEFAULT NULL,
  3_2_o_supply_safety_box_stock_out_year varchar(100) DEFAULT NULL,
  3_2_p_supply_functional_ari_timer_in_stock varchar(100) DEFAULT NULL,
  3_2_p_supply_functional_ari_timer_stock_out_month varchar(100) DEFAULT NULL,
  3_2_p_supply_functional_ari_timer_stock_out_day varchar(100) DEFAULT NULL,
  3_2_p_supply_functional_ari_timer_stock_out_year varchar(100) DEFAULT NULL,
  3_2_q_supply_rapid_diagnostic_test_in_stock varchar(100) DEFAULT NULL,
  3_2_q_supply_rapid_diagnostic_test_stock_out_month varchar(100) DEFAULT NULL,
  3_2_q_supply_rapid_diagnostic_test_stock_out_day varchar(100) DEFAULT NULL,
  3_2_q_supply_rapid_diagnostic_test_stock_out_year varchar(100) DEFAULT NULL,
  3_3_supply_chss_cbis_booklet varchar(100) DEFAULT NULL,
  4_1_supervision_updated_workplan varchar(100) DEFAULT NULL,
  4_2_supervision_not_able_conduct varchar(100) DEFAULT NULL,
  4_2_b_supervision_motorbike_not_equipped varchar(100) DEFAULT NULL,
  4_2_b_supervision_motorbike_not_functioning varchar(100) DEFAULT NULL,
  4_2_b_supervision_motorbike_unable_ride_alone varchar(100) DEFAULT NULL,
  4_2_b_supervision_motorbike_no_fuel varchar(100) DEFAULT NULL,
  4_2_b_supervision_community_too_far varchar(100) DEFAULT NULL,
  4_2_b_supervision_form_not_enough varchar(100) DEFAULT NULL,
  4_2_b_supervision_cha_too_many varchar(100) DEFAULT NULL,
  4_2_b_supervision_oic_not_available_chss_needed_facility varchar(100) DEFAULT NULL,
  4_2_b_supervision_chss_health_status varchar(100) DEFAULT NULL,
  4_2_b_supervision_cha_not_available varchar(100) DEFAULT NULL,
  4_2_b_supervision_other_checkbox varchar(100) DEFAULT NULL,
  4_2_b_supervision_other_reason varchar(100) DEFAULT NULL,
  4_2_c_supervision_motorbike_problem_how_coduct varchar(100) DEFAULT NULL,
  4_3_supervision_chss_community_day_1 varchar(100) DEFAULT NULL,
  4_3_supervision_chss_community_day_2 varchar(100) DEFAULT NULL,
  4_3_supervision_chss_community_day_3 varchar(100) DEFAULT NULL,
  4_3_supervision_chss_community_day_4 varchar(100) DEFAULT NULL,
  4_3_supervision_chss_community_day_5 varchar(100) DEFAULT NULL,
  4_3_supervision_chss_facility_day_1 varchar(100) DEFAULT NULL,
  4_3_supervision_chss_facility_day_2 varchar(100) DEFAULT NULL,
  4_3_supervision_chss_facility_day_3 varchar(100) DEFAULT NULL,
  4_3_supervision_chss_facility_day_4 varchar(100) DEFAULT NULL,
  4_3_supervision_chss_facility_day_5 varchar(100) DEFAULT NULL,
  4_4_supervision_chss_community_day_1 varchar(100) DEFAULT NULL,
  4_4_supervision_chss_community_day_2 varchar(100) DEFAULT NULL,
  4_4_supervision_chss_community_day_3 varchar(100) DEFAULT NULL,
  4_4_supervision_chss_community_day_4 varchar(100) DEFAULT NULL,
  4_4_supervision_chss_community_day_5 varchar(100) DEFAULT NULL,
  4_4_supervision_oic_facility_day_1 varchar(100) DEFAULT NULL,
  4_4_supervision_oic_facility_day_2 varchar(100) DEFAULT NULL,
  4_4_supervision_oic_facility_day_3 varchar(100) DEFAULT NULL,
  4_4_supervision_oic_facility_day_4 varchar(100) DEFAULT NULL,
  4_4_supervision_oic_facility_day_5 varchar(100) DEFAULT NULL,
  5_1_recruitment_chss_number_catchment varchar(100) DEFAULT NULL,
  5_2_recruitment_cha_number_catchment varchar(100) DEFAULT NULL,
  5_3_recruitment_chv_number_catchment_ttm varchar(100) DEFAULT NULL,
  5_3_recruitment_chv_number_catchment_other varchar(100) DEFAULT NULL,
  6_1_me_chss_supervision_report_always varchar(100) DEFAULT NULL,
  6_1_me_chss_supervision_report_sometimes varchar(100) DEFAULT NULL,
  6_1_me_chss_supervision_report_rarely varchar(100) DEFAULT NULL,
  1_1_health_education_outreach_talk varchar(100) DEFAULT NULL,
  1_1_b_health_education_outreach_talk_topic varchar(100) DEFAULT NULL,
  1_2_health_education_outreach_talk_plan_visible varchar(100) DEFAULT NULL,
  1_3_health_education_outreach_talk_topic_facility_report varchar(100) DEFAULT NULL,
  1_3_health_education_outreach_talk_topic_other varchar(100) DEFAULT NULL,
  1_3_b_health_education_outreach_talk_other_description varchar(100) DEFAULT NULL,
  1_4_health_education_outreach_facility_demo_topic varchar(100) DEFAULT NULL,
  1_4_b_health_education_outreach_facility_demo_topic_name varchar(100) DEFAULT NULL,
  1_5_health_education_outreach_facility_client_daily_10_15 varchar(100) DEFAULT NULL,
  1_5_health_education_outreach_facility_client_daily_16_20 varchar(100) DEFAULT NULL,
  1_5_health_education_outreach_facility_client_daily_21_30 varchar(100) DEFAULT NULL,
  1_5_health_education_outreach_facility_client_daily_31_plus varchar(100) DEFAULT NULL,
  1_6_health_education_outreach_staff_talk varchar(100) DEFAULT NULL,
  1_6_b_health_education_outreach_staff_talk_person varchar(100) DEFAULT NULL,
  1_6_c_health_education_outreach_staff_talk_person_one_week varchar(100) DEFAULT NULL,
  1_6_c_health_education_outreach_staff_talk_person_two_week varchar(100) DEFAULT NULL,
  1_6_c_health_education_outreach_staff_talk_person_one_month varchar(100) DEFAULT NULL,
  1_6_c_health_education_outreach_staff_talk_person_three_month varchar(100) DEFAULT NULL,
  1_7_health_education_outreach_iec_material_healthy_life_logo varchar(100) DEFAULT NULL,
  1_8_health_education_outreach_document_wash_env_health_package varchar(100) DEFAULT NULL,
  1_8_health_education_outreach_document_community_health_policy varchar(100) DEFAULT NULL,
  1_8_health_education_outreach_document_community_health_strategy varchar(100) DEFAULT NULL,
  1_8_health_education_outreach_document_national_health_promotion varchar(100) DEFAULT NULL,
  1_8_health_education_outreach_document_media_tool_kit varchar(100) DEFAULT NULL,
  1_8_health_education_outreach_document_national_health_strategy varchar(100) DEFAULT NULL,
  1_1_vector_contol_facility_mapping varchar(100) DEFAULT NULL,
  1_1_a_vector_contol_facility_fumigated_sanitized_sprayed varchar(100) DEFAULT NULL,
  1_2_vector_contol_facility_observed varchar(100) DEFAULT NULL,
  2_1_sanitation_health_waste_separated varchar(100) DEFAULT NULL,
  2_2_sanitation_health_waste_stored varchar(100) DEFAULT NULL,
  2_3_sanitation_functional_incinerator varchar(100) DEFAULT NULL,
  2_4_sanitation_staff_trained_infection_prevention_control varchar(100) DEFAULT NULL,
  2_5_sanitation_staff_trained_dead_body_swabbing varchar(100) DEFAULT NULL,
  2_6_sanitation_facility_death_number varchar(100) DEFAULT NULL,
  2_7_sanitation_hand_washing_station varchar(100) DEFAULT NULL,
  2_8_sanitation_functional_gender_sensitive_latrine varchar(100) DEFAULT NULL,
  2_9_sanitation_condition_facility_satisfactory varchar(100) DEFAULT NULL,
  3_1_health_occupational_safety_personal_protection_equipment varchar(100) DEFAULT NULL,
  3_2_health_occupational_safety_staff_medical_examination_record varchar(100) DEFAULT NULL,
  3_3_health_occupational_safety_record_workplace_injury_sickness varchar(100) DEFAULT NULL,
  4_1_water_quality_safe_drinking_water varchar(100) DEFAULT NULL,
  4_1_b_water_quality_safe_drinking_water_acceptable varchar(100) DEFAULT NULL,
  4_1_c_water_quality_water_point_analyzed varchar(100) DEFAULT NULL,
  4_1_d_water_quality_safe_drinking_water_year_round varchar(100) DEFAULT NULL,
  4_1_e_water_quality_safe_drinking_water_fenced_locked varchar(100) DEFAULT NULL,
  4_2_water_quality_staff_trained_analysis varchar(100) DEFAULT NULL,
  4_2_b_water_quality_staff_reagent_functional_testing_kit varchar(100) DEFAULT NULL,
  4_3_water_quality_water_point_disinfected varchar(100) DEFAULT NULL,
  note longtext,

  primary key ( id )
  
)  
engine = federated
connection='mysql://liberiad_admin:Ju!y261847@97.74.233.76:3306/liberiad_upload/de_integrated_supervision_tool_facility'
;
