/*

  Federated table federated_de_integrated_supervision_tool_community connects to a table of the same name 
  in the same schema liberiad_upload on the MySQL instance on server 97.74.233.76.  This server
  host the liberiamohdata.com website where the IFI data is collected.
  
*/

use lastmile_liberiamohdata;

drop table if exists federated_de_integrated_supervision_tool_community;

create table federated_de_integrated_supervision_tool_community (

  id int( 10 )            not null auto_increment,
  
  meta_uuid               varchar(255)  NOT NULL,
  meta_de_init            varchar(100)  DEFAULT NULL,
  meta_de_date            varchar(100)  DEFAULT NULL,
  meta_de_time_start      time          DEFAULT NULL,
  meta_de_time_end        time          DEFAULT NULL,
  meta_qa_init            varchar(100)  DEFAULT NULL,
  meta_qa_date            varchar(100)  DEFAULT NULL,
  meta_data_source        varchar(100)  DEFAULT NULL,
  meta_form_version       varchar(100)  DEFAULT NULL,
  meta_insert_date_time   datetime      DEFAULT NULL,
  
  data_collector_team varchar(100) DEFAULT NULL,
  county varchar(100) DEFAULT NULL,
  health_district varchar(100) DEFAULT NULL,
  community varchar(100) DEFAULT NULL,
  month_complete varchar(100) DEFAULT NULL,
  day_complete varchar(100) DEFAULT NULL,
  year_complete varchar(100) DEFAULT NULL,
  cha_id varchar(100) DEFAULT NULL,
  chss_id varchar(100) DEFAULT NULL,
  cha varchar(100) DEFAULT NULL,
  cha_gender varchar(100) DEFAULT NULL,
  chss varchar(100) DEFAULT NULL,
  chss_gender varchar(100) DEFAULT NULL,
  data_collector_name varchar(100) DEFAULT NULL,
  data_collector_position varchar(100) DEFAULT NULL,
  supervision_time_start varchar(100) DEFAULT NULL,
  supervision_time_end varchar(100) DEFAULT NULL,
  
  1_1_community_engagement_chc_established varchar(100) DEFAULT NULL,
  1_1_b_community_engagement_chc_number_meeting_last_month varchar(100) DEFAULT NULL,
  1_2_community_engagement_chc_cha_know_function varchar(100) DEFAULT NULL,
  2_1_a_supply_microlut_ocp_in_stock varchar(100) DEFAULT NULL,
  2_1_a_supply_microlut_ocp_stock_out_month varchar(100) DEFAULT NULL,
  2_1_a_supply_microlut_ocp_stock_out_day varchar(100) DEFAULT NULL,
  2_1_a_supply_microlut_ocp_stock_out_year varchar(100) DEFAULT NULL,
  2_1_b_supply_microgynon_ocp_in_stock varchar(100) DEFAULT NULL,
  2_1_b_supply_microgynon_ocp_stock_out_month varchar(100) DEFAULT NULL,
  2_1_b_supply_microgynon_ocp_stock_out_day varchar(100) DEFAULT NULL,
  2_1_b_supply_microgynon_ocp_stock_out_year varchar(100) DEFAULT NULL,
  2_1_c_supply_male_condom_in_stock varchar(100) DEFAULT NULL,
  2_1_c_supply_male_condom_stock_out_month varchar(100) DEFAULT NULL,
  2_1_c_supply_male_condom_stock_out_day varchar(100) DEFAULT NULL,
  2_1_c_supply_male_condom_stock_out_year varchar(100) DEFAULT NULL,
  2_1_d_supply_female_condom_in_stock varchar(100) DEFAULT NULL,
  2_1_d_supply_female_condom_stock_out_month varchar(100) DEFAULT NULL,
  2_1_d_supply_female_condom_stock_out_day varchar(100) DEFAULT NULL,
  2_1_d_supply_female_condom_stock_out_year varchar(100) DEFAULT NULL,
  2_1_e_supply_disposable_glove_in_stock varchar(100) DEFAULT NULL,
  2_1_e_supply_disposable_glove_stock_out_month varchar(100) DEFAULT NULL,
  2_1_e_supply_disposable_glove_stock_out_day varchar(100) DEFAULT NULL,
  2_1_e_supply_disposable_glove_stock_out_year varchar(100) DEFAULT NULL,
  2_1_f_supply_act_25_67_5_mg_tablet_in_stock varchar(100) DEFAULT NULL,
  2_1_f_supply_act_25_67_5_mg_tablet_stock_out_month varchar(100) DEFAULT NULL,
  2_1_f_supply_act_25_67_5_mg_tablet_stock_out_day varchar(100) DEFAULT NULL,
  2_1_f_supply_act_25_67_5_mg_tablet_stock_out_year varchar(100) DEFAULT NULL,
  2_1_g_supply_act_50_135_mg_tablet_in_stock varchar(100) DEFAULT NULL,
  2_1_g_supply_act_50_135_mg_tablet_stock_out_month varchar(100) DEFAULT NULL,
  2_1_g_supply_act_50_135_mg_tablet_stock_out_day varchar(100) DEFAULT NULL,
  2_1_g_supply_act_50_135_mg_tablet_stock_out_year varchar(100) DEFAULT NULL,
  2_1_h_supply_artesunate_100_mg_suppository_in_stock varchar(100) DEFAULT NULL,
  2_1_h_supply_artesunate_100_mg_suppository_stock_out_month varchar(100) DEFAULT NULL,
  2_1_h_supply_artesunate_100_mg_suppository_stock_out_day varchar(100) DEFAULT NULL,
  2_1_h_supply_artesunate_100_mg_suppository_stock_out_year varchar(100) DEFAULT NULL,
  2_1_i_supply_amox_250_mg_dispersible_tablet_in_stock varchar(100) DEFAULT NULL,
  2_1_i_supply_amox_250_mg_dispersible_tablet_stock_out_month varchar(100) DEFAULT NULL,
  2_1_i_supply_amox_250_mg_dispersible_tablet_stock_out_day varchar(100) DEFAULT NULL,
  2_1_i_supply_amox_250_mg_dispersible_tablet_stock_out_year varchar(100) DEFAULT NULL,
  2_1_j_supply_ors_20_6_1l_sachet_in_stock varchar(100) DEFAULT NULL,
  2_1_j_supply_ors_20_6_1l_sachet_stock_out_month varchar(100) DEFAULT NULL,
  2_1_j_supply_ors_20_6_1l_sachet_stock_out_day varchar(100) DEFAULT NULL,
  2_1_j_supply_ors_20_6_1l_sachet_stock_out_year varchar(100) DEFAULT NULL,
  2_1_k_supply_zinc_sulfate_20_mg_scored_tablet_in_stock varchar(100) DEFAULT NULL,
  2_1_k_supply_zinc_sulfate_20_mg_scored_tablet_stock_out_month varchar(100) DEFAULT NULL,
  2_1_k_supply_zinc_sulfate_20_mg_scored_tablet_stock_out_day varchar(100) DEFAULT NULL,
  2_1_k_supply_zinc_sulfate_20_mg_scored_tablet_stock_out_year varchar(100) DEFAULT NULL,
  2_1_l_supply_paracetamol_100_mg_disp_tablet_in_stock varchar(100) DEFAULT NULL,
  2_1_l_supply_paracetamol_100_mg_disp_tablet_stock_out_month varchar(100) DEFAULT NULL,
  2_1_l_supply_paracetamol_100_mg_disp_tablet_stock_out_day varchar(100) DEFAULT NULL,
  2_1_l_supply_paracetamol_100_mg_disp_tablet_stock_out_year varchar(100) DEFAULT NULL,
  2_1_m_supply_muac_strap_in_stock varchar(100) DEFAULT NULL,
  2_1_m_supply_muac_strap_stock_out_month varchar(100) DEFAULT NULL,
  2_1_m_supply_muac_strap_stock_out_day varchar(100) DEFAULT NULL,
  2_1_m_supply_muac_strap_stock_out_year varchar(100) DEFAULT NULL,
  2_1_n_supply_dispensing_bag_in_stock varchar(100) DEFAULT NULL,
  2_1_n_supply_dispensing_bag_stock_out_month varchar(100) DEFAULT NULL,
  2_1_n_supply_dispensing_bag_stock_out_day varchar(100) DEFAULT NULL,
  2_1_n_supply_dispensing_bag_stock_out_year varchar(100) DEFAULT NULL,
  2_1_o_supply_safety_box_in_stock varchar(100) DEFAULT NULL,
  2_1_o_supply_safety_box_stock_out_month varchar(100) DEFAULT NULL,
  2_1_o_supply_safety_box_stock_out_day varchar(100) DEFAULT NULL,
  2_1_o_supply_safety_box_stock_out_year varchar(100) DEFAULT NULL,
  2_1_p_supply_functional_ari_timer_in_stock varchar(100) DEFAULT NULL,
  2_1_p_supply_functional_ari_timer_stock_out_month varchar(100) DEFAULT NULL,
  2_1_p_supply_functional_ari_timer_stock_out_day varchar(100) DEFAULT NULL,
  2_1_p_supply_functional_ari_timer_stock_out_year varchar(100) DEFAULT NULL,
  2_1_q_supply_rapid_diagnostic_test_in_stock varchar(100) DEFAULT NULL,
  2_1_q_supply_rapid_diagnostic_test_stock_out_month varchar(100) DEFAULT NULL,
  2_1_q_supply_rapid_diagnostic_test_stock_out_day varchar(100) DEFAULT NULL,
  2_1_q_supply_rapid_diagnostic_test_stock_out_year varchar(100) DEFAULT NULL,
  2_2_supply_restock_month_last varchar(100) DEFAULT NULL,
  2_2_supply_restock_day_last varchar(100) DEFAULT NULL,
  2_2_supply_restock_year_last varchar(100) DEFAULT NULL,
  3_1_supervision_chss_4_week varchar(100) DEFAULT NULL,
  3_2_supervision_cha_workplan_updated varchar(100) DEFAULT NULL,
  3_3_supervision_chss_review_form varchar(100) DEFAULT NULL,
  3_4_supervision_chss_feedback_work varchar(100) DEFAULT NULL,
  3_5_supervision_chss_referred_patient varchar(100) DEFAULT NULL,
  3_6_supervision_chss_supported varchar(100) DEFAULT NULL,
  3_7_supervision_cha_msr_in_community varchar(100) DEFAULT NULL,
  3_7_supervision_cha_msr_outside_community varchar(100) DEFAULT NULL,
  4_1_incentive_correct_amount varchar(100) DEFAULT NULL,
  4_2_incentive_on_time varchar(100) DEFAULT NULL,
  4_3_incentive_month varchar(100) DEFAULT NULL,
  4_3_incentive_day varchar(100) DEFAULT NULL,
  4_3_incentive_year varchar(100) DEFAULT NULL,
  4_4_incentive_where_pick_up varchar(100) DEFAULT NULL,
  4_5_incentive_amount varchar(100) DEFAULT NULL,
  5_1_a_me_cbis_form_household_registration varchar(100) DEFAULT NULL,
  5_1_d_me_cbis_form_module_2 varchar(100) DEFAULT NULL,
  5_1_b_me_cbis_form_routine_visit varchar(100) DEFAULT NULL,
  5_1_e_me_cbis_form_module_3 varchar(100) DEFAULT NULL,
  5_1_c_me_cbis_form_referral_msr varchar(100) DEFAULT NULL,
  5_1_f_me_cbis_form_module_4 varchar(100) DEFAULT NULL,
  5_2_a_me_module_1_job_aid varchar(100) DEFAULT NULL,
  5_2_c_me_module_3_job_aid varchar(100) DEFAULT NULL,
  5_2_b_me_module_2_job_aid varchar(100) DEFAULT NULL,
  5_2_d_me_module_4_job_aid varchar(100) DEFAULT NULL,
  5_2_e_me_bcc_tools varchar(100) DEFAULT NULL,
  5_3_me_module_3_row_marked_form_1 varchar(100) DEFAULT NULL,
  5_3_me_module_3_row_marked_form_2 varchar(100) DEFAULT NULL,
  5_3_me_module_3_row_marked_form_3 varchar(100) DEFAULT NULL,
  5_4_me_module_3_row_bolded_box_form_1 varchar(100) DEFAULT NULL,
  5_4_me_module_3_row_bolded_box_form_2 varchar(100) DEFAULT NULL,
  5_4_me_module_3_row_bolded_box_form_3 varchar(100) DEFAULT NULL,
  6_1_service_delivery_trained_module_1 varchar(100) DEFAULT NULL,
  6_1_service_delivery_trained_module_2 varchar(100) DEFAULT NULL,
  6_1_service_delivery_trained_module_3 varchar(100) DEFAULT NULL,
  6_1_service_delivery_trained_module_4 varchar(100) DEFAULT NULL,
  6_2_service_delivery_question_1 varchar(100) DEFAULT NULL,
  6_2_service_delivery_question_2 varchar(100) DEFAULT NULL,
  6_2_service_delivery_question_3 varchar(100) DEFAULT NULL,
  6_2_service_delivery_question_4 varchar(100) DEFAULT NULL,
  6_3_service_delivery_read_entire varchar(100) DEFAULT NULL,
  6_3_service_delivery_read_part varchar(100) DEFAULT NULL,
  6_3_service_delivery_cant_read varchar(100) DEFAULT NULL,
  6_4_service_delivery_cha_visit_client_1 varchar(100) DEFAULT NULL,
  6_4_service_delivery_cha_visit_client_2 varchar(100) DEFAULT NULL,
  6_4_service_delivery_cha_visit_client_3 varchar(100) DEFAULT NULL,
  6_4_service_delivery_cha_visit_client_4 varchar(100) DEFAULT NULL,
  6_4_service_delivery_cha_visit_client_5 varchar(100) DEFAULT NULL,
  7_1_recruitment_cha_selected_community varchar(100) DEFAULT NULL,
  7_2_recruitment_cha_number_community varchar(100) DEFAULT NULL,
  1_1_health_education_outreach_facility_visit_talk_client_1 varchar(100) DEFAULT NULL,
  1_1_health_education_outreach_facility_visit_talk_client_2 varchar(100) DEFAULT NULL,
  1_1_health_education_outreach_facility_visit_talk_client_3 varchar(100) DEFAULT NULL,
  1_1_b_health_education_outreach_facility_visit_talk_topic varchar(100) DEFAULT NULL,
  1_2_health_education_outreach_community_talk_client_1 varchar(100) DEFAULT NULL,
  1_2_health_education_outreach_community_talk_client_2 varchar(100) DEFAULT NULL,
  1_2_health_education_outreach_community_talk_client_3 varchar(100) DEFAULT NULL,
  1_2_b_health_education__community_talk_topic varchar(100) DEFAULT NULL,
  1_3_health_education_outreach_message_radio_client_1 varchar(100) DEFAULT NULL,
  1_3_health_education_outreach_message_radio_client_2 varchar(100) DEFAULT NULL,
  1_3_health_education_outreach_message_radio_client_3 varchar(100) DEFAULT NULL,
  1_3_b_health_education_outreach_message_radio_topic varchar(100) DEFAULT NULL,
  1_4_health_education_outreach_iec_material_logo_client_1 varchar(100) DEFAULT NULL,
  1_4_health_education_outreach_iec_material_logo_client_2 varchar(100) DEFAULT NULL,
  1_4_health_education_outreach_iec_material_logo_client_3 varchar(100) DEFAULT NULL,
  1_5_health_education_outreach_person_talk_health_issue_client_1 varchar(100) DEFAULT NULL,
  1_5_health_education_outreach_person_talk_health_issue_client_2 varchar(100) DEFAULT NULL,
  1_5_health_education_outreach_person_talk_health_issue_client_3 varchar(100) DEFAULT NULL,
  1_5_b_health_education_outreach_person_talk_health_issue_topic varchar(100) DEFAULT NULL,
  1_1_vector_contol_community_mapping varchar(100) DEFAULT NULL,
  1_1_a_vector_contol_community_fumigated_sanitized_sprayed varchar(100) DEFAULT NULL,
  1_2_vector_contol_community_person_trained varchar(100) DEFAULT NULL,
  2_1_sanitation_open_defecation_free varchar(100) DEFAULT NULL,
  2_2_sanitation_declared_open_defecation_free varchar(100) DEFAULT NULL,
  2_2_b_sanitation_declared_open_defecation_free_month varchar(100) DEFAULT NULL,
  2_2_b_sanitation_declared_open_defecation_free_day varchar(100) DEFAULT NULL,
  2_2_b_sanitation_declared_open_defecation_free_year varchar(100) DEFAULT NULL,
  2_3_sanitation_number_trained_dead_body_swabbing varchar(100) DEFAULT NULL,
  2_4_sanitation_community_number_garbage_disposal_site varchar(100) DEFAULT NULL,
  2_5_sanitation_community_practice_hand_washing varchar(100) DEFAULT NULL,
  2_6_sanitation_community_number_latrine varchar(100) DEFAULT NULL,
  2_7_sanitation_community_number_hand_wash_facility varchar(100) DEFAULT NULL,
  2_8_sanitation_community_natural_leader varchar(100) DEFAULT NULL,
  2_8_b_sanitation_community_natural_leader_functional varchar(100) DEFAULT NULL,
  2_9_sanitation_community_satisfactory varchar(100) DEFAULT NULL,
  3_1_water_quality_access_safe_drinking varchar(100) DEFAULT NULL,
  3_1_b_water_quality_access_safe_drinking_acceptable_all varchar(100) DEFAULT NULL,
  3_1_c_water_quality_access_safe_drinking_water_point_disinfected varchar(100) DEFAULT NULL,
  3_1_d_water_quality_access_safe_drinking_water_point_analyzed varchar(100) DEFAULT NULL,
  3_1_e_water_quality_access_safe_drinking_year_round varchar(100) DEFAULT NULL,
  3_1_f_water_quality_access_safe_drinking_fenced_locked varchar(100) DEFAULT NULL,
  3_2_water_quality_viable_community_wash_committee varchar(100) DEFAULT NULL,
  3_3_water_quality_wash_entrepreneur_hand_pump_mechanic varchar(100) DEFAULT NULL,
  3_4_water_quality_hand_pump_spare_part varchar(100) DEFAULT NULL,
  3_5_water_quality_treatment_product varchar(100) DEFAULT NULL,
  4_1_food_safety_handler_trained_hygiene_client_1 varchar(100) DEFAULT NULL,
  4_1_food_safety_handler_trained_hygiene_client_2 varchar(100) DEFAULT NULL,
  4_1_food_safety_handler_trained_hygiene_client_3 varchar(100) DEFAULT NULL,
  4_2_food_safety_regular_monitor_client_1 varchar(100) DEFAULT NULL,
  4_2_food_safety_regular_monitor_client_2 varchar(100) DEFAULT NULL,
  4_2_food_safety_regular_monitor_client_3 varchar(100) DEFAULT NULL,
  4_3_food_safety_establishment_certified_deoh_moh_1 varchar(100) DEFAULT NULL,
  4_3_food_safety_establishment_certified_deoh_moh_2 varchar(100) DEFAULT NULL,
  4_3_food_safety_establishment_certified_deoh_moh_3 varchar(100) DEFAULT NULL,
  1_1_rapport_introduce_self_cha_chv varchar(100) DEFAULT NULL,
  1_2_rapport_ask_permission_hold_session varchar(100) DEFAULT NULL,
  1_3_rapport_ensure_full_participation varchar(100) DEFAULT NULL,
  1_4_rapport_maintain_professionalism varchar(100) DEFAULT NULL,
  2_1_relevance_keep_audience_interested varchar(100) DEFAULT NULL,
  2_2_relevance_communicate_level_audience varchar(100) DEFAULT NULL,
  2_3_relevance_right_message_target_audience varchar(100) DEFAULT NULL,
  2_4_relevance_draw_experience_audience varchar(100) DEFAULT NULL,
  3_1_message_delivery_logical_sequence_dialog_framework varchar(100) DEFAULT NULL,
  3_2_message_delivery_key_message_dialog_framework varchar(100) DEFAULT NULL,
  3_3_message_delivery_affirmation_effective varchar(100) DEFAULT NULL,
  3_4_message_delivery_open_ended_question_effective varchar(100) DEFAULT NULL,
  3_5_message_delivery_reflective_listen_effective varchar(100) DEFAULT NULL,
  3_6_message_delivery_summary_effective varchar(100) DEFAULT NULL,
  3_7_message_delivery_not_introduce_additional_irrelevant_message varchar(100) DEFAULT NULL,
  3_8_message_delivery_accurate_refer_not_know_answer varchar(100) DEFAULT NULL,
  3_9_message_delivery_nonverbal_communication varchar(100) DEFAULT NULL,
  4_1_functional_performance_cover_house_community_effective varchar(100) DEFAULT NULL,
  4_2_functional_performance_manage_time_efficient varchar(100) DEFAULT NULL,
  
  note longtext,
 
  primary key ( id )
  
)  
engine = federated
connection='mysql://liberiad_admin:Ju!y261847@97.74.233.76:3306/liberiad_upload/de_integrated_supervision_tool_community'
;
