/*

  Federated table federated_de_integrated_supervision_tool_facility_spot_check connects to a table of the same name 
  in the same schema liberiad_upload on the MySQL instance on server 97.74.233.76.  This server
  host the liberiamohdata.com website where the IFI data is collected.
  
*/

use lastmile_liberiamohdata;

drop table if exists federated_de_integrated_supervision_tool_facility_spot_check;

create table federated_de_integrated_supervision_tool_facility_spot_check (

  id int( 10 )            not null auto_increment,
  
  meta_uuid varchar(255) NOT NULL,
  meta_de_init varchar(100) DEFAULT NULL,
  meta_de_date varchar(100) DEFAULT NULL,
  meta_de_time_start time DEFAULT NULL,
  meta_de_time_end time DEFAULT NULL,
  meta_qa_init varchar(100) DEFAULT NULL,
  meta_qa_date varchar(100) DEFAULT NULL,
  meta_data_source varchar(100) DEFAULT NULL,
  meta_form_version varchar(100) DEFAULT NULL,
  meta_insert_date_time datetime DEFAULT NULL,
  county varchar(100) DEFAULT NULL,
  health_district varchar(100) DEFAULT NULL,
  facility varchar(100) DEFAULT NULL,
  month_complete varchar(100) DEFAULT NULL,
  day_complete varchar(100) DEFAULT NULL,
  year_complete varchar(100) DEFAULT NULL,
  chss_id varchar(100) DEFAULT NULL,
  chss varchar(100) DEFAULT NULL,
  chss_gender varchar(100) DEFAULT NULL,
  oic varchar(100) DEFAULT NULL,
  oic_gender varchar(100) DEFAULT NULL,
  data_collector_name varchar(100) DEFAULT NULL,
  data_collector_position varchar(100) DEFAULT NULL,
  visit_verification varchar(100) DEFAULT NULL,
  supply_locked_box_cha varchar(100) DEFAULT NULL,
  supply_microlut_ocp_in_stock varchar(100) DEFAULT NULL,
  supply_microlut_ocp_stock_out_month varchar(100) DEFAULT NULL,
  supply_microlut_ocp_stock_out_day varchar(100) DEFAULT NULL,
  supply_microlut_ocp_stock_out_year varchar(100) DEFAULT NULL,
  supply_microgynon_ocp_in_stock varchar(100) DEFAULT NULL,
  supply_microgynon_ocp_stock_out_month varchar(100) DEFAULT NULL,
  supply_microgynon_ocp_stock_out_day varchar(100) DEFAULT NULL,
  supply_microgynon_ocp_stock_out_year varchar(100) DEFAULT NULL,
  supply_male_condom_in_stock varchar(100) DEFAULT NULL,
  supply_male_condom_stock_out_month varchar(100) DEFAULT NULL,
  supply_male_condom_stock_out_day varchar(100) DEFAULT NULL,
  supply_male_condom_stock_out_year varchar(100) DEFAULT NULL,
  supply_female_condom_in_stock varchar(100) DEFAULT NULL,
  supply_female_condom_stock_out_month varchar(100) DEFAULT NULL,
  supply_female_condom_stock_out_day varchar(100) DEFAULT NULL,
  supply_female_condom_stock_out_year varchar(100) DEFAULT NULL,
  supply_disposable_glove_in_stock varchar(100) DEFAULT NULL,
  supply_disposable_glove_stock_out_month varchar(100) DEFAULT NULL,
  supply_disposable_glove_stock_out_day varchar(100) DEFAULT NULL,
  supply_disposable_glove_stock_out_year varchar(100) DEFAULT NULL,
  supply_act_25_67_5_mg_tablet_in_stock varchar(100) DEFAULT NULL,
  supply_act_25_67_5_mg_tablet_stock_out_month varchar(100) DEFAULT NULL,
  supply_act_25_67_5_mg_tablet_stock_out_day varchar(100) DEFAULT NULL,
  supply_act_25_67_5_mg_tablet_stock_out_year varchar(100) DEFAULT NULL,
  supply_act_50_135_mg_tablet_in_stock varchar(100) DEFAULT NULL,
  supply_act_50_135_mg_tablet_stock_out_month varchar(100) DEFAULT NULL,
  supply_act_50_135_mg_tablet_stock_out_day varchar(100) DEFAULT NULL,
  supply_act_50_135_mg_tablet_stock_out_year varchar(100) DEFAULT NULL,
  supply_artesunate_100_mg_suppository_in_stock varchar(100) DEFAULT NULL,
  supply_artesunate_100_mg_suppository_stock_out_month varchar(100) DEFAULT NULL,
  supply_artesunate_100_mg_suppository_stock_out_day varchar(100) DEFAULT NULL,
  supply_artesunate_100_mg_suppository_stock_out_year varchar(100) DEFAULT NULL,
  supply_amox_250_mg_dispersible_tablet_in_stock varchar(100) DEFAULT NULL,
  supply_amox_250_mg_dispersible_tablet_stock_out_month varchar(100) DEFAULT NULL,
  supply_amox_250_mg_dispersible_tablet_stock_out_day varchar(100) DEFAULT NULL,
  supply_amox_250_mg_dispersible_tablet_stock_out_year varchar(100) DEFAULT NULL,
  supply_ors_20_6_1l_sachet_in_stock varchar(100) DEFAULT NULL,
  supply_ors_20_6_1l_sachet_stock_out_month varchar(100) DEFAULT NULL,
  supply_ors_20_6_1l_sachet_stock_out_day varchar(100) DEFAULT NULL,
  supply_ors_20_6_1l_sachet_stock_out_year varchar(100) DEFAULT NULL,
  supply_zinc_sulfate_20_mg_scored_tablet_in_stock varchar(100) DEFAULT NULL,
  supply_zinc_sulfate_20_mg_scored_tablet_stock_out_month varchar(100) DEFAULT NULL,
  supply_zinc_sulfate_20_mg_scored_tablet_stock_out_day varchar(100) DEFAULT NULL,
  supply_zinc_sulfate_20_mg_scored_tablet_stock_out_year varchar(100) DEFAULT NULL,
  supply_paracetamol_100_mg_disp_tablet_in_stock varchar(100) DEFAULT NULL,
  supply_paracetamol_100_mg_disp_tablet_stock_out_month varchar(100) DEFAULT NULL,
  supply_paracetamol_100_mg_disp_tablet_stock_out_day varchar(100) DEFAULT NULL,
  supply_paracetamol_100_mg_disp_tablet_stock_out_year varchar(100) DEFAULT NULL,
  supply_muac_strap_in_stock varchar(100) DEFAULT NULL,
  supply_muac_strap_stock_out_month varchar(100) DEFAULT NULL,
  supply_muac_strap_stock_out_day varchar(100) DEFAULT NULL,
  supply_muac_strap_stock_out_year varchar(100) DEFAULT NULL,
  supply_dispensing_bag_in_stock varchar(100) DEFAULT NULL,
  supply_dispensing_bag_stock_out_month varchar(100) DEFAULT NULL,
  supply_dispensing_bag_stock_out_day varchar(100) DEFAULT NULL,
  supply_dispensing_bag_stock_out_year varchar(100) DEFAULT NULL,
  supply_safety_box_in_stock varchar(100) DEFAULT NULL,
  supply_safety_box_stock_out_month varchar(100) DEFAULT NULL,
  supply_safety_box_stock_out_day varchar(100) DEFAULT NULL,
  supply_safety_box_stock_out_year varchar(100) DEFAULT NULL,
  supply_functional_ari_timer_in_stock varchar(100) DEFAULT NULL,
  supply_functional_ari_timer_stock_out_month varchar(100) DEFAULT NULL,
  supply_functional_ari_timer_stock_out_day varchar(100) DEFAULT NULL,
  supply_functional_ari_timer_stock_out_year varchar(100) DEFAULT NULL,
  supply_rapid_diagnostic_test_in_stock varchar(100) DEFAULT NULL,
  supply_rapid_diagnostic_test_stock_out_month varchar(100) DEFAULT NULL,
  supply_rapid_diagnostic_test_stock_out_day varchar(100) DEFAULT NULL,
  supply_rapid_diagnostic_test_stock_out_year varchar(100) DEFAULT NULL,
  note longtext,

  primary key ( id )
  
)  
engine = federated
connection='mysql://liberiad_admin:Ju!y261847@97.74.233.76:3306/liberiad_upload/de_integrated_supervision_tool_facility_spot_check'
;
